# Generated by Django 3.1.3 on 2021-02-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jusik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jusik_list',
            name='buy_date',
            field=models.DateField(),
        ),
    ]
