# Generated by Django 3.1.3 on 2021-02-25 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jusik', '0002_auto_20210225_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='jusik_list',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
