# Generated by Django 3.1.3 on 2021-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jusik', '0003_remove_jusik_list_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jusik_list',
            name='date',
            field=models.DateField(default='2020-02-23'),
        ),
    ]
