# Generated by Django 3.1.3 on 2021-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jusik', '0005_auto_20210226_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='jusik_list',
            name='amount_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jusik_list',
            name='amount_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jusik_list',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
