# Generated by Django 3.1.3 on 2021-03-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jusik', '0006_auto_20210301_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='jusik_list',
            name='present_price',
            field=models.IntegerField(default=0),
        ),
    ]
