# Generated by Django 3.1.3 on 2021-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jusik', '0007_jusik_list_present_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jusik_list',
            name='stock_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jusik_list',
            name='present_price',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
