# Generated by Django 3.1.3 on 2021-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jusik', '0008_auto_20210329_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jusik_list',
            name='stock_code',
            field=models.CharField(default='005930', max_length=6),
        ),
    ]
