# Generated by Django 3.1.3 on 2021-10-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedlist',
            old_name='palatability',
            new_name='liking',
        ),
    ]
