# Generated by Django 3.1.3 on 2021-08-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlist',
            name='palatability',
            field=models.CharField(choices=[('LIKE', '좋아!'), ('DISLIKE', '그냥 그래..'), ('HATE', '싫어!')], max_length=7),
        ),
    ]
