# Generated by Django 3.1.3 on 2021-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutineapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutine',
            name='content',
        ),
        migrations.AddField(
            model_name='rutine',
            name='color',
            field=models.CharField(default='red', max_length=150),
        ),
    ]
