# Generated by Django 3.1.3 on 2021-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutine',
            name='detail',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rutine',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
