# Generated by Django 3.1.3 on 2021-06-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutineapp', '0003_auto_20210611_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutine',
            name='color',
        ),
    ]
