# Generated by Django 3.1.3 on 2021-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutineapp', '0004_remove_rutine_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutine',
            name='color',
            field=models.CharField(default='red', max_length=150, null=True),
        ),
    ]
