# Generated by Django 3.1.3 on 2021-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutineapp', '0005_rutine_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='red', max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rutine',
            name='color',
        ),
    ]
