# Generated by Django 3.1.3 on 2021-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcalendarapp', '0005_auto_20210616_1434'),
        ('rutineapp', '0006_auto_20210616_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AddField(
            model_name='rutine',
            name='color',
            field=models.CharField(default='red', max_length=150, null=True),
        ),
    ]
