# Generated by Django 3.1.5 on 2021-01-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210119_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hit_counter',
            field=models.IntegerField(default=0),
        ),
    ]
