# Generated by Django 3.1.3 on 2021-06-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(max_length=500, null=True)),
                ('time', models.IntegerField(default=0)),
                ('color', models.CharField(default='black', max_length=150, null=True)),
            ],
        ),
    ]
