# Generated by Django 3.1.3 on 2021-06-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutineapp', '0003_auto_20210611_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='시작시간')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='rutineapp.rutine')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title1', to='rutineapp.rutine')),
            ],
        ),
    ]
