# Generated by Django 3.1.3 on 2021-06-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='날짜')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title1', to='routineapp.routine')),
            ],
        ),
    ]
