# Generated by Django 3.1.3 on 2021-06-16 16:08

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='날짜')),
                ('color', colorfield.fields.ColorField(choices=[('#FF0000', 'red'), ('#FFA500', 'orange'), ('#FFFF00', 'yellow'), ('#34A223', 'green'), ('#0000FF', 'blue'), ('#00498C', 'navy'), ('#8B00FF', 'red'), ('#000000', 'black')], default='#FFFFFF', max_length=18)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title1', to='rutineapp.rutine')),
            ],
        ),
    ]
