# Generated by Django 3.1.3 on 2021-06-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutineapp', '0003_auto_20210611_1508'),
        ('newcalendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='rutineapp.rutine'),
        ),
    ]
