# Generated by Django 3.1.3 on 2021-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcalendarapp', '0002_auto_20210613_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateField(verbose_name='날짜'),
        ),
    ]
