# Generated by Django 3.1.3 on 2021-06-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newcalendarapp', '0002_calendarmodel_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarmodel',
            name='color',
        ),
    ]
