# Generated by Django 3.1.3 on 2021-06-11 16:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newcalendarapp', '0003_auto_20210611_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', max_length=18),
        ),
    ]
