# Generated by Django 3.1.3 on 2021-06-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newcalendarapp', '0003_remove_calendarmodel_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmodel',
            old_name='start_time',
            new_name='start_day',
        ),
    ]
