# Generated by Django 3.1.3 on 2021-07-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newcalendarapp', '0004_auto_20210629_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmodel',
            old_name='start_day',
            new_name='start_time',
        ),
    ]
